apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: supply-chain-backend
  template:
    metadata:
      labels:
        app: supply-chain-backend
    spec:
      containers:
      - name: supply-chain-backend
        image: supply-chain-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: supply-chain-secrets
              key: database-url
        - name: BLOCKCHAIN_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: supply-chain-config
              key: blockchain-provider
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: supply-chain-config
              key: kafka-brokers
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: supply-chain-secrets
              key: redis-url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: supply-chain-backend
spec:
  selector:
    app: supply-chain-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
